### ISSUE TITLE
No HTTPS/SSL, should add through shell access

### ISSUE THREAD

**Issue by Superjig** [Superjig/DutchFGCWebsite#1]
@JoeriR I believe can add a HTTPS certificate through https://letsencrypt.org/getting-started/
Should be doable with shell access. Increases our search engine findability

**Comment by JoeriR** [comment]
HTTPS has been implemented on the server using CertBot.
![image](https://user-images.githubusercontent.com/16247005/182034007-c734b4a2-972f-45ae-a7b8-d96040202c20.png)

This tutorial was used to setup and install CertBot:
https://certbot.eff.org/instructions?ws=nginx&os=ubuntubionic

Certbot will automatically update the certificate.
(If it fails then I'll receive an e-mail)
